### ISSUE TITLE
grid package v3.2.3

### ISSUE THREAD

**Issue by tinyheero** [infotroph/ggplotTicks#6]
Hi,

I can't install this as the DESCRIPTION specifies grid version 3.2.3. I think grid became a base package in R (http://stackoverflow.com/questions/29349398/r-package-grid-disappeared) as of 1.8. Hence, I think you are actually trying to specify R version 3.2.3 and not necessarily grid 3.2.3? I have R 3.2.2 right now.

**Comment by infotroph** [comment]
Looks like I got carried away requiring things -- as far I know it should be fine on any version of R recent enough to run ggplot2 v2.0.

I've removed the Grid version requirement -- Can you give it a try and report back?

**Comment by tinyheero** [comment]
Yup it works! Thanks!

**Comment by infotroph** [comment]
Woohoo! You're my first confirmed user, so I'd love feedback on what does and doesn't work for you.
